server:
  port: 8282

spring:
  application:
    name: ORDER-SERVICE
#  config: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost/vineet_db
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  eureka:
    instance:
      prefer-ip-address:true
    client:
      fetch-registry: true
      registry-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


logging:
  file:
    name: order-service.log