server:
  port: 8484

spring:
  application:
    name: PRODUCT-SERVICE
#  config: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost/vineet_db
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  eureka:
    instance:
      prefer-ip-address:true
    client:
      fetch-registry: true
      registry-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        event-consumer-buffer-size: 5
        failure-rate-threshold: 5
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: time-based

#resilience4j:
#  circuitbreaker:
#    instances:
#      productCircuitBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 3
#        minimumNumberOfCalls: 5
#        slidingWindowType: COUNT_BASED
#
#      paymentCircuitBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        failureRateThreshold: 60
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 2
#        minimumNumberOfCalls: 5
#        slidingWindowType: COUNT_BASED